name: Merge Develop to Staging

on:
  workflow_dispatch:

jobs:
  merge_to_staging:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Merge develop to staging
      run: |
        git checkout staging
        git merge --no-ff develop --no-commit
        
        if git diff --name-only --diff-filter=U | grep .; then
          echo "Merge conflicts detected"
          echo "Merge conflicts detected in the merge from develop to staging branch. Please resolve conflicts manually." | mail -s "Merge Conflicts Detected" reddyrajashekar114@gmail.com
          exit 1
        fi
        
        git commit -m "Merge branch 'develop' into staging"
        git push origin staging

